CREATE DATABASE CSDL_WEB
GO
USE CSDL_WEB
GO
GO
CREATE TABLE PhanQuyen(
MaPQ INT IDENTITY PRIMARY KEY,
LoaiQuyen INT NOT NULL,
TenPQ NVARCHAR(50) NOT NULL,
)
GO
CREATE TABLE TaiKhoan
(
MaTK INT IDENTITY PRIMARY KEY,
TaiKhoan NVARCHAR(50) UNIQUE NOT NULL,
MatKhau NVARCHAR(50) NOT NULL,
MaPQ INT REFERENCES PhanQuyen(MaPQ),
HoTen NVARCHAR(50) NOT NULL,
NamSinh DATE NULL,
DiaChi NVARCHAR(200) NULL,
Block NVARCHAR(5) NOT NULL,
)

CREATE TABLE NSX
(
MaNSX INT IDENTITY PRIMARY KEY,
TenNSX NVARCHAR(50) NOT NULL,
DiaChi NVARCHAR(200) NOT NULL,
)
CREATE TABLE HangHoa
(
MaSP INT IDENTITY PRIMARY KEY,
MaNSX INT FOREIGN KEY REFERENCES NSX(MaNSX),
TenSP NVARCHAR(50) NOT NULL,
GiaBan MONEY NOT NULL,
GiaGoc MONEY NOT NULL,
SoLuong INT NOT NULL,
CPU CHAR(50) NOT NULL,
RAM CHAR(50) NOT NULL,
OCung CHAR(50) NOT NULL,
ManHinh CHAR(50) NOT NULL,
PIN CHAR(50) NOT NULL,
)

CREATE TABLE HangHoaImage(
MaSP INT FOREIGN KEY REFERENCES HangHoa(MaSP),
Hinh varbinary(MAX) NOT NULL,
)

CREATE TABLE DonNhap(
MaGiaoDich INT IDENTITY PRIMARY KEY,
NgayGiaoDich DATE NOT NULL DEFAULT GETDATE(),
TongTien INT NOT NULL CHECK(TongTien >= 0),
ViTriKho NVARCHAR(200) NOT NULL,
)
GO

CREATE TABLE Nhap(
MaGiaoDich INT FOREIGN KEY REFERENCES dbo.DonNhap(MaGiaoDich),
MaSP INT FOREIGN KEY REFERENCES dbo.HangHoa(MaSP),
SoLuong INT,
PRIMARY KEY(MaGiaoDich, MaSP)
)
CREATE TABLE PTTT
(
MaPTTT INT IDENTITY PRIMARY KEY,
TenPTTT NVARCHAR(50) NOT NULL,
)
CREATE TABLE KhuyenMai
(
MaKhuyenMai INT IDENTITY PRIMARY KEY,
GiaTriKhuyenMai INT NOT NULL,
NgayBatDau DATE NOT NULL,
NgayKetThuc DATE NOT NULL,
)

CREATE TABLE GioHang
(
MaGioHang INT IDENTITY PRIMARY KEY,
MaKhuyenMai INT REFERENCES KhuyenMai(MaKhuyenMai),
TongTien MONEY DEFAULT 0,
ThoiGian DATE NOT NULL,
MaPTTT INT FOREIGN KEY REFERENCES PTTT(MaPTTT) ,
DiaChi NVARCHAR(200) NOT NULL,
TrangThai NVARCHAR(100) NOT NULL,
)
CREATE TABLE GioHangInfo(
MaGioHang INT FOREIGN KEY REFERENCES dbo.GioHang(MaGioHang),
MaSP INT FOREIGN KEY REFERENCES dbo.HangHoa(MaSP),
SoLuong INT NULL,
)

CREATE TABLE BinhLuan
(
MaSP INT REFERENCES HangHoa(MaSP),
MaTK INT REFERENCES TaiKhoan(MaTK),
PRIMARY KEY(MaSP, MaTK,LanMua),
TieuDe NVARCHAR(100) NULL,
NoiDung NVARCHAR(1000) NULL,
Sao INT NULL,
LanMua INT,
)
CREATE TABLE YeuThich(
MaSP INT REFERENCES HangHoa(MaSP),
MaTK INT REFERENCES TaiKhoan(MaTK),
ThoiGian DATE NULL,
PRIMARY KEY(MaSP, MaTK)
)